### ISSUE TITLE
Update GPU Usage and other Specs of R2 and Borah

### ISSUE THREAD

**Issue by Eli-Woodard** [bsurc/docs#15]
- [x] Add up-to-date information to [Scheduling_a_Job](https://github.com/Eli-Woodard/docs/blob/main/docs/Cluster%20Guides/Scheduling_a_Job.md)

**Comment by jennyfothergill** [comment]
This is fixed in #12, but I think we could also port over the info table from https://www.boisestate.edu/rcs/hpc/

**Comment by jennyfothergill** [comment]
Done by #34
